### PR TITLE
add mouseUp and mouseDown

### PR DESCRIPTION
**Pull request by stephenkingsley**
I think add mouseUp and mouseDown event is convenient for this project.

### CODE REVIEW

**Comment by mjackson** [comment]
Why do you think this change is necessary? Can't you just add these events directly to your child component?

```js
<PointTarget ...>
  <div onMouseUp={...}/>
</PointTarget>
```

**Comment by stephenkingsley** [comment]
because in the PointTarget had click event, so mouseUp or down is a part of click event.

**Comment by mjackson** [comment]
@stephenkingsley We're just cloning whatever element you give us and passing in an `onClick` prop. If you want to use `onMouseUp` or `onMouseDown` you can do so using the example above.

**Comment by stephenkingsley** [comment]
may I ask you what is the purpose of creating `PointTarget`. just the `click event`?

**Comment by battaile** [comment]
@stephenkingsley  https://github.com/ReactTraining/react-point/issues/2

**Comment by stephenkingsley** [comment]
maybe I knew what is the purpose of this component. and I agree it that the component is not need other event. and if I want to join your group, has any problem?

**Pull request closed without merging**
